language: csharp
dotnet: 2.0.0
sudo: false  # use the new container-based Travis infrastructure 

solution: ./src/Isop.sln
install:
  - msbuild /t:restore src

script: 
  - msbuild src
  - dotnet test -f netcoreapp1.1 src/Tests/Tests.csproj
