version: 1.0.{build}
image: Visual Studio 2022
before_build:
  - ps: >-
      $buildId = $env:APPVEYOR_BUILD_NUMBER.PadLeft(5, '0');
      $versionSuffixPR = "PR$($env:APPVEYOR_PULL_REQUEST_NUMBER)-$buildId";
      $branchName = "$env:APPVEYOR_REPO_BRANCH".Replace("_","");
      $versionSuffixBRANCH = "$branchName-$buildId";
      $env:VersionSuffix = if ("$env:APPVEYOR_REPO_TAG" -eq "true") { "" } else { if ("$env:APPVEYOR_PULL_REQUEST_NUMBER") { $versionSuffixPR } else { $versionSuffixBRANCH } };
  - msbuild /t:restore . 
configuration: Release
build:
  project: Isop.sln
  verbosity: minimal
  publish_nuget: true
test_script:
  - dotnet test --configuration Debug tests/Tests
nuget:
  account_feed: false
  project_feed: true
  disable_publish_on_pr: true
branches:
  only: 
    - master
    - isop